# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170529_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver2',
        ),
    ]
