# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170531_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_type',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
