# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170531_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_type',
            name='label_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
