# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_report_type_label_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
