# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_pet_pet_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
