# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20170531_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='report_type',
        ),
    ]
