# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20170531_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coat',
            old_name='title',
            new_name='coat_title',
        ),
        migrations.RenameField(
            model_name='pet_breed',
            old_name='title',
            new_name='breed_title',
        ),
    ]
